export const demoReport = {
  metadata: {
    generatedAt: "2026-04-25T16:40:00Z",
    repository: "sample-data",
    revision: "demo-main",
    historyMode: "full",
  },
  summary: {
    totalCommitsScanned: 420,
    relevantCommits: 37,
    uniqueDefects: 19,
    components: 4,
    authors: 7,
    periodStart: "2026-03-01",
    periodEnd: "2026-04-24",
    coverageRatio: 0.0881,
  },
  componentInsights: [
    {
      component: "src/scanner",
      commits: 12,
      uniqueDefects: 8,
      filesTouched: 14,
      authors: 4,
      totalChurn: 638,
      activeDays: 11,
      hotspotScore: 39.24,
      topAuthors: ["A. Chen", "M. Diaz", "S. Patel"],
      topFiles: [
        "src/scanner/repository_scanner.cpp",
        "src/scanner/tag_parser.cpp",
        "src/scanner/git_client.cpp",
      ],
    },
    {
      component: "src/api",
      commits: 9,
      uniqueDefects: 6,
      filesTouched: 10,
      authors: 3,
      totalChurn: 411,
      activeDays: 8,
      hotspotScore: 29.88,
      topAuthors: ["M. Diaz", "L. Brown"],
      topFiles: [
        "src/api/report_controller.cpp",
        "src/api/http_router.cpp",
      ],
    },
    {
      component: "src/analytics",
      commits: 8,
      uniqueDefects: 5,
      filesTouched: 9,
      authors: 3,
      totalChurn: 352,
      activeDays: 7,
      hotspotScore: 25.61,
      topAuthors: ["S. Patel", "A. Chen"],
      topFiles: [
        "src/analytics/hotspot_service.cpp",
        "src/analytics/summary_engine.cpp",
      ],
    },
    {
      component: "frontend/dashboard",
      commits: 8,
      uniqueDefects: 4,
      filesTouched: 11,
      authors: 4,
      totalChurn: 284,
      activeDays: 9,
      hotspotScore: 22.49,
      topAuthors: ["L. Brown", "J. Kim"],
      topFiles: [
        "frontend/src/app.js",
        "frontend/src/demo-data.js",
      ],
    },
  ],
  authorInsights: [
    {
      author: "A. Chen",
      commits: 11,
      uniqueDefects: 8,
      components: 3,
      totalChurn: 544,
      topComponents: ["src/scanner", "src/analytics"],
    },
    {
      author: "M. Diaz",
      commits: 8,
      uniqueDefects: 6,
      components: 2,
      totalChurn: 438,
      topComponents: ["src/api", "src/scanner"],
    },
    {
      author: "S. Patel",
      commits: 7,
      uniqueDefects: 5,
      components: 2,
      totalChurn: 341,
      topComponents: ["src/analytics", "src/scanner"],
    },
    {
      author: "L. Brown",
      commits: 6,
      uniqueDefects: 4,
      components: 2,
      totalChurn: 273,
      topComponents: ["frontend/dashboard", "src/api"],
    },
  ],
  timeline: [
    { date: "2026-04-18", commits: 3, defectRefs: 4 },
    { date: "2026-04-19", commits: 4, defectRefs: 5 },
    { date: "2026-04-20", commits: 6, defectRefs: 8 },
    { date: "2026-04-21", commits: 5, defectRefs: 7 },
    { date: "2026-04-22", commits: 7, defectRefs: 10 },
    { date: "2026-04-23", commits: 6, defectRefs: 8 },
    { date: "2026-04-24", commits: 6, defectRefs: 9 },
  ],
  commits: [
    {
      hash: "d6f0c7b1a2c3",
      author: "A. Chen",
      authoredAt: "2026-04-24T18:12:30Z",
      subject: "Harden scanner fallback for [art123456] correlation",
      message:
        "Harden scanner fallback for [art123456] correlation and preserve issue link #248 during batch runs.",
      parents: ["a1b2c3d4e5f6"],
      defectIds: ["ART-123456"],
      issueRefs: [248],
      components: ["src/scanner", "src/api"],
      totalChurn: 69,
      files: [
        {
          path: "src/scanner/repository_scanner.cpp",
          component: "src/scanner",
          fileKind: "code",
          added: 42,
          deleted: 11,
          churn: 53,
        },
        {
          path: "src/api/report_controller.cpp",
          component: "src/api",
          fileKind: "code",
          added: 13,
          deleted: 3,
          churn: 16,
        },
      ],
    },
    {
      hash: "e7a1b2c3d4e5",
      author: "M. Diaz",
      authoredAt: "2026-04-23T14:40:02Z",
      subject: "Tune hotspot ranking after ART-123777 review",
      message:
        "Tune hotspot ranking after ART-123777 review so component density and churn do not overreact to one noisy merge.",
      parents: ["a0f9e8d7c6b5"],
      defectIds: ["ART-123777"],
      issueRefs: [],
      components: ["src/analytics"],
      totalChurn: 35,
      files: [
        {
          path: "src/analytics/hotspot_service.cpp",
          component: "src/analytics",
          fileKind: "code",
          added: 28,
          deleted: 7,
          churn: 35,
        },
      ],
    },
    {
      hash: "f8b2c3d4e5f6",
      author: "L. Brown",
      authoredAt: "2026-04-22T09:04:55Z",
      subject: "Refresh dashboard filters for [art124110] and issue #251",
      message:
        "Refresh dashboard filters for [art124110] and issue #251 to keep frontend and API summaries aligned.",
      parents: ["9b8a7c6d5e4f"],
      defectIds: ["ART-124110"],
      issueRefs: [251],
      components: ["frontend/dashboard", "src/api"],
      totalChurn: 55,
      files: [
        {
          path: "frontend/src/app.js",
          component: "frontend/dashboard",
          fileKind: "code",
          added: 33,
          deleted: 12,
          churn: 45,
        },
        {
          path: "src/api/http_router.cpp",
          component: "src/api",
          fileKind: "code",
          added: 8,
          deleted: 2,
          churn: 10,
        },
      ],
    },
  ],
  insightSummary: {
    available: true,
    source: "built-in",
    narrative:
      "The strongest concentration of defect-linked activity is in src/scanner, where eight unique customer markers appear across twelve commits. The pattern looks like repeated stabilization work rather than a one-off incident.",
    highlights: [
      "src/scanner leads the backlog of recurring defect-linked commits and also has the highest churn.",
      "A. Chen appears on the largest share of defect-linked work, which is useful for review routing and ownership mapping.",
      "The last seven days show steady daily signal volume rather than one single spike, which often points to sustained reliability work.",
    ],
    nextActions: [
      "Review the top scanner files first because they combine repeat defect tags with high change volume.",
      "Compare scanner hotspots with recent API changes to see whether interface churn is amplifying defect work.",
      "Turn the current daily scan into a scheduled background job before scaling to additional repositories.",
    ],
  },
};

